kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: airflow-postgres
  template:
    metadata:
      labels:
        name: airflow-postgres
        deploy: airflow-postgres
    spec:
      restartPolicy: Always
      containers:
        - name: postgres
          image: rhel8/postgresql-13:1-62
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_USER
              value: airflow
            - name: POSTGRESQL_PASSWORD
              value: airflow
            - name: POSTGRESQL_DATABASE
              value: airflow

---
kind: Service
apiVersion: v1
metadata:
  name: airflow-postgres
spec:
  selector:
    name: airflow-postgres
  ports:
  - name: airflow-postgres
    protocol: TCP
    port: 5432
    targetPort: 5432